// AUTO-GENERATED from /tmp/parse-sheets.js — Bond Job Changes + Salary Analysis sheets.
// Do not edit by hand. When Salesforce sync lands, this fixture is replaced by the live API.

export const bondAlumni = [
  {
    "fellow": "Diandre Miller",
    "role": "☆  at LMP Tech",
    "organization": "LMP Tech",
    "yearStart": "2024",
    "yearEnd": "Present",
    "startDate": "2024-09-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 13000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Contractor",
    "isaEligible": false,
    "cohort": "9",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": null,
    "totalBondInvoice": null,
    "bondPayments": null,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": null,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Talia Pichardo",
    "role": "☆ Stem Specialist at New York Edge",
    "organization": "New York Edge",
    "yearStart": "2023",
    "yearEnd": "Present",
    "startDate": "2023-10-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 19500,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": null,
    "isaEligible": false,
    "cohort": "7",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1603.13,
    "totalBondInvoice": 6412.52,
    "bondPayments": 4809,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": null,
    "currentlyInvoicing": false
  },
  {
    "fellow": "AnJu Hyppolite",
    "role": "Civic Innovation Corps Fellow at NJ Office of Innovation",
    "organization": "NJ Office of Innovation",
    "yearStart": "2022",
    "yearEnd": "2022",
    "startDate": "2022-06-01",
    "endDate": "2022-09-01",
    "isCurrent": false,
    "salary": 36400,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": false,
    "cohort": "7",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": null,
    "totalBondInvoice": null,
    "bondPayments": null,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": null,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Tony Hoang",
    "role": "☆ Digital Engineering Accelerated Program Internship at CVS Health",
    "organization": "CVS Health",
    "yearStart": "2024",
    "yearEnd": "Present",
    "startDate": "2024-05-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 47840,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": false,
    "cohort": "9",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": null,
    "totalBondInvoice": null,
    "bondPayments": 0,
    "bondSalaryThreshold": null,
    "incomeSharePct": null,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Jailene DeVine-Jones",
    "role": "☆ O2A Trainee at GalaxE Solutions",
    "organization": "GalaxE Solutions",
    "yearStart": "2022",
    "yearEnd": "2023",
    "startDate": "2022-06-01",
    "endDate": "2023-01-01",
    "isCurrent": false,
    "salary": 50000,
    "salaryBand": "$50–60k",
    "permTemp": "Permanent",
    "employeeType": null,
    "isaEligible": false,
    "cohort": "7",
    "commit": false,
    "employedStatus": "Former",
    "monthlyBondInvoice": 208.33,
    "totalBondInvoice": 0,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 5,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Rae Charles",
    "role": "☆ Software Engineer Apprentice at Interapt",
    "organization": "Interapt",
    "yearStart": "2022",
    "yearEnd": "2023",
    "startDate": "2022-11-01",
    "endDate": "2023-11-01",
    "isCurrent": false,
    "salary": 50000,
    "salaryBand": "$50–60k",
    "permTemp": "Temporary",
    "employeeType": "Contractor",
    "isaEligible": false,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Former",
    "monthlyBondInvoice": 208.33,
    "totalBondInvoice": 2499.96,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 5,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Tashawnee Guarriello",
    "role": "☆ Software Developer at FDM Group",
    "organization": "FDM Group",
    "yearStart": "2023",
    "yearEnd": "2023",
    "startDate": "2023-02-01",
    "endDate": "2023-04-01",
    "isCurrent": false,
    "salary": 50000,
    "salaryBand": "$50–60k",
    "permTemp": "Temporary",
    "employeeType": "Contractor",
    "isaEligible": false,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Former",
    "monthlyBondInvoice": 208.33,
    "totalBondInvoice": 0,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 5,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Jalamang Janka",
    "role": "☆ Java Developer at Ascendion",
    "organization": "Ascendion",
    "yearStart": "2023",
    "yearEnd": "Present",
    "startDate": "2023-04-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 50000,
    "salaryBand": "$50–60k",
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": false,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 208.33,
    "totalBondInvoice": 5833.24,
    "bondPayments": 5515,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 5,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Vanessa Watson",
    "role": "☆ Data and Team Administrator at Open Apparel Registry",
    "organization": "Open Apparel Registry",
    "yearStart": "2022",
    "yearEnd": "2023",
    "startDate": "2022-01-01",
    "endDate": "2023-02-01",
    "isCurrent": false,
    "salary": 55000,
    "salaryBand": "$50–60k",
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": false,
    "cohort": "7",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 229,
    "totalBondInvoice": 2290,
    "bondPayments": 458,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 5,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Imran Nazir",
    "role": "☆ Associate Software Developer at Infosys Foundation",
    "organization": "Infosys Foundation",
    "yearStart": "2021",
    "yearEnd": "2024",
    "startDate": "2021-06-01",
    "endDate": "2024-02-01",
    "isCurrent": false,
    "salary": 57000,
    "salaryBand": "$50–60k",
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": false,
    "cohort": "7",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 237.5,
    "totalBondInvoice": null,
    "bondPayments": null,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 5,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Christine Taylor",
    "role": "☆ Technical Customer Support Specialist at Spotnana",
    "organization": "Spotnana",
    "yearStart": "2023",
    "yearEnd": "Present",
    "startDate": "2023-07-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 57000,
    "salaryBand": "$50–60k",
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": false,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 237.5,
    "totalBondInvoice": null,
    "bondPayments": 688,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 5,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Stephanie Marie Lucano",
    "role": "Attendance Coordinator at New Vision Charter High Schools",
    "organization": "New Vision Charter High Schools",
    "yearStart": "2022",
    "yearEnd": "2023",
    "startDate": "2022-08-01",
    "endDate": "2023-07-01",
    "isCurrent": false,
    "salary": 57500,
    "salaryBand": "$50–60k",
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": false,
    "cohort": "8",
    "commit": false,
    "employedStatus": null,
    "monthlyBondInvoice": 562.5,
    "totalBondInvoice": 16516.69,
    "bondPayments": 14267,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 5,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Stephanie Marie Lucano",
    "role": "Attendance Coordinator at New Vision Charter High Schools",
    "organization": "New Vision Charter High Schools",
    "yearStart": "2023",
    "yearEnd": "Present",
    "startDate": "2023-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 60375,
    "salaryBand": "$60–70k",
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": false,
    "employedStatus": null,
    "monthlyBondInvoice": 562.5,
    "totalBondInvoice": 16516.69,
    "bondPayments": 14267,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 10,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Isaac Guerrero",
    "role": "☆ Application Developer Associate at Accenture",
    "organization": "Accenture",
    "yearStart": "2023",
    "yearEnd": "Present",
    "startDate": "2023-04-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 65000,
    "salaryBand": "$60–70k",
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 541.67,
    "totalBondInvoice": null,
    "bondPayments": 7573,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 10,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Jan-Carlos Matias",
    "role": "☆ Apprentice Software Developer at The Beyond Group",
    "organization": "The Beyond Group",
    "yearStart": "2023",
    "yearEnd": "Present",
    "startDate": "2023-09-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 65000,
    "salaryBand": "$60–70k",
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 541.67,
    "totalBondInvoice": 19500.12,
    "bondPayments": 12448,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 10,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Derek Tran",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": "2023",
    "yearEnd": "Present",
    "startDate": "2023-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 65781,
    "salaryBand": "$60–70k",
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 548.18,
    "totalBondInvoice": null,
    "bondPayments": null,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 10,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Silis Kleemoff",
    "role": "☆ Junior Software Developer at Metro Group",
    "organization": "Metro Group",
    "yearStart": "2024",
    "yearEnd": "2025",
    "startDate": "2024-06-01",
    "endDate": "2025-03-01",
    "isCurrent": false,
    "salary": 67000,
    "salaryBand": "$60–70k",
    "permTemp": "Permanent",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "9",
    "commit": false,
    "employedStatus": "Former",
    "monthlyBondInvoice": 525,
    "totalBondInvoice": 3150,
    "bondPayments": 2100,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 10,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Adrian Burke",
    "role": "☆ Software Engineer at Verizon",
    "organization": "Verizon",
    "yearStart": "2024",
    "yearEnd": "Present",
    "startDate": "2024-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 72000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 900,
    "totalBondInvoice": 9000,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Christina Loiacono",
    "role": "☆ Back End Engineering Intern at New York Times",
    "organization": "New York Times",
    "yearStart": "2024",
    "yearEnd": "2024",
    "startDate": "2024-06-01",
    "endDate": "2024-08-01",
    "isCurrent": false,
    "salary": 72800,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1000,
    "totalBondInvoice": 1000,
    "bondPayments": 990,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Akira Brown",
    "role": "☆ Software Engineer at Red Canary, Inc.",
    "organization": "Red Canary, Inc.",
    "yearStart": "2025",
    "yearEnd": "Present",
    "startDate": "2025-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 75000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 937.5,
    "totalBondInvoice": 6552.5,
    "bondPayments": 6552.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Xavier Rice",
    "role": "☆ Safety Operations Associate at Feeld",
    "organization": "Feeld",
    "yearStart": "2025",
    "yearEnd": "Present",
    "startDate": "2025-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 75845,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 948.06,
    "totalBondInvoice": 2844.18,
    "bondPayments": 2844.18,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Damien Yule",
    "role": "☆ Software Engineer at Scanbuy",
    "organization": "Scanbuy",
    "yearStart": "2022",
    "yearEnd": "Present",
    "startDate": "2022-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 80000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1000,
    "totalBondInvoice": 34000,
    "bondPayments": 2600,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Qi Zhong",
    "role": "☆ Software Engineer at Citizens Bank",
    "organization": "Citizens Bank",
    "yearStart": "2025",
    "yearEnd": "Present",
    "startDate": "2025-07-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 80000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1000,
    "totalBondInvoice": 1000,
    "bondPayments": 1000,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Ryan Fodera",
    "role": "☆ Project Controller at Mace North America Limited",
    "organization": "Mace North America Limited",
    "yearStart": "2024",
    "yearEnd": "Present",
    "startDate": "2024-10-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 80000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1000,
    "totalBondInvoice": 10000,
    "bondPayments": 8970,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": true
  },
  {
    "fellow": "Taylor Williams",
    "role": "☆ Junior Software Engineer at Morning Brew",
    "organization": "Morning Brew",
    "yearStart": "2022",
    "yearEnd": "2023",
    "startDate": "2022-08-01",
    "endDate": "2023-03-01",
    "isCurrent": false,
    "salary": 80000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1000,
    "totalBondInvoice": 6000,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Anita Owen",
    "role": "☆ Full Stack Engineer at iCapital",
    "organization": "iCapital",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-02-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 85000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1062.5,
    "totalBondInvoice": 6365,
    "bondPayments": 6365,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Chantal Gomez",
    "role": "☆ Software Engineer at Red Canary, Inc.",
    "organization": "Red Canary, Inc.",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 85000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1062.5,
    "totalBondInvoice": 8500,
    "bondPayments": 5312.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Christina Loiacono",
    "role": "☆ Analyst: Enterprise Technology & Security Development Program at Citizens Bank",
    "organization": "Citizens Bank",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-07-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 85000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1000,
    "totalBondInvoice": 1000,
    "bondPayments": 990,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Destiny Joyner",
    "role": "☆ Full Stack Engineer at iCapital",
    "organization": "iCapital",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-02-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 85000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1062.5,
    "totalBondInvoice": 7437.5,
    "bondPayments": 6365,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Justin Overton",
    "role": "☆ Analyst: Enterprise Technology & Security Development Program at Citizens Bank",
    "organization": "Citizens Bank",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-07-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 85000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1000,
    "totalBondInvoice": 2000,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Ki Sub Lee",
    "role": "☆ Software Engineer at Dwolla",
    "organization": "Dwolla",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": "2023-01-01",
    "isCurrent": true,
    "salary": 85000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1062.5,
    "totalBondInvoice": 1062.5,
    "bondPayments": 1062.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Riley Lovell",
    "role": "☆ Software Engineer at Dwolla",
    "organization": "Dwolla",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": "2023-01-01",
    "isCurrent": true,
    "salary": 85000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1062.5,
    "totalBondInvoice": 4250,
    "bondPayments": 4250,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Tony Taylor",
    "role": "☆ Junior Software Developer at New York City Council",
    "organization": "New York City Council",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 85000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "9",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1062.5,
    "totalBondInvoice": 12750,
    "bondPayments": 5312.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Emalee Soto",
    "role": "☆ QA Engineer at Poll Everywhere",
    "organization": "Poll Everywhere",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-03-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 87000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1087.5,
    "totalBondInvoice": 16312.5,
    "bondPayments": 6525,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Jeremy Montes",
    "role": "☆ Engineering Apprentice at Airbnb",
    "organization": "Airbnb",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-04-01",
    "endDate": "2025-10-01",
    "isCurrent": true,
    "salary": 87360,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1092,
    "totalBondInvoice": 3276,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Teyanna Earle",
    "role": "☆ Engineering Apprentice at Airbnb",
    "organization": "Airbnb",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-04-01",
    "endDate": "2025-10-01",
    "isCurrent": true,
    "salary": 87360,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1092,
    "totalBondInvoice": 1092,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Oliver Chuzan",
    "role": "☆ Entry Level Software Developer at Deloitte Consulting LLP",
    "organization": "Deloitte Consulting LLP",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 87550,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1094.38,
    "totalBondInvoice": 32338,
    "bondPayments": 32318.84,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Anthony Cannonier",
    "role": "☆ Schools Senior Data Specialist at Democracy Prep Public Schools",
    "organization": "Democracy Prep Public Schools",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-07-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1125,
    "totalBondInvoice": 6750,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Benny Zheng",
    "role": "☆ Software Engineer at David Energy",
    "organization": "David Energy",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-09-01",
    "endDate": "2023-10-01",
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1125,
    "totalBondInvoice": 27652,
    "bondPayments": 26870,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Derek Tran",
    "role": "☆ Technology Summer Analyst -C00 Summer Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-06-01",
    "endDate": "2023-08-01",
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1125,
    "totalBondInvoice": 15875,
    "bondPayments": 6275,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "John Prado",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1125,
    "totalBondInvoice": 19940,
    "bondPayments": 13162.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Joshuel Marte",
    "role": "☆ Software Engineer at David Energy",
    "organization": "David Energy",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-09-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1125,
    "totalBondInvoice": 40500,
    "bondPayments": 39375,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Juan Feliz",
    "role": "☆ Software Engineer at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1352,
    "totalBondInvoice": 25688,
    "bondPayments": 1352,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Ray Udeogu",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1000,
    "totalBondInvoice": 29200,
    "bondPayments": 11800,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Rebecca Garcia",
    "role": "☆ Cybersecurity Intern at NYC Department of Social Services",
    "organization": "NYC Department of Social Services",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-03-01",
    "endDate": "2024-05-01",
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1125,
    "totalBondInvoice": 0,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Rose Durandisse",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1125,
    "totalBondInvoice": 18000,
    "bondPayments": 4300,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Stephanie Reyes",
    "role": "☆ Software Engineering Fellow at Spotify",
    "organization": "Spotify",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": "2023-03-01",
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "8",
    "commit": false,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1125,
    "totalBondInvoice": 6750,
    "bondPayments": 6750,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Yesenia Lopez Rodriguez",
    "role": "☆ Software Engineer I at Ana Luisa",
    "organization": "Ana Luisa",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-03-01",
    "endDate": "2022-07-01",
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": false,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1125,
    "totalBondInvoice": 3375,
    "bondPayments": 2250,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Zane Ahmed",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 90000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1125,
    "totalBondInvoice": 29250,
    "bondPayments": 2205,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Poonam Dass",
    "role": "☆ Software Engineer at Wells Fargo",
    "organization": "Wells Fargo",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2021-11-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 90002,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1125,
    "totalBondInvoice": 45000,
    "bondPayments": 43875,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Adam Tahiri",
    "role": "☆ SWE Apprentice at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-01-01",
    "endDate": "2022-08-01",
    "isCurrent": true,
    "salary": 91520,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1144,
    "totalBondInvoice": 0,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Candy Agard",
    "role": "☆ SWE Apprentice at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-01-01",
    "endDate": "2022-08-01",
    "isCurrent": true,
    "salary": 91520,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1144,
    "totalBondInvoice": 31580,
    "bondPayments": 4576,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Daniel Naranjo",
    "role": "☆ SWE Apprentice at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-01-01",
    "endDate": "2022-12-01",
    "isCurrent": true,
    "salary": 91520,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1144,
    "totalBondInvoice": 6910,
    "bondPayments": 5766,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Geormary Sanchez",
    "role": "☆ SWE Apprentice at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-01-01",
    "endDate": "2022-08-01",
    "isCurrent": true,
    "salary": 91520,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1144,
    "totalBondInvoice": 27456,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Jordan Bobadilla Rosario",
    "role": "☆ SWE Apprentice at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-01-01",
    "endDate": "2022-08-01",
    "isCurrent": true,
    "salary": 91520,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1144,
    "totalBondInvoice": 16016,
    "bondPayments": 6858,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Obie Rustemi",
    "role": "☆ SWE Apprentice at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-01-01",
    "endDate": "2023-10-01",
    "isCurrent": true,
    "salary": 91520,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1144,
    "totalBondInvoice": 33724,
    "bondPayments": 5706,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Yashiry Azize",
    "role": "☆ SWE Apprentice at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-01-01",
    "endDate": "2024-03-01",
    "isCurrent": true,
    "salary": 91520,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1144,
    "totalBondInvoice": 26312,
    "bondPayments": 18876,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Hady Mohamed",
    "role": "☆ Software Engineer at Poll Everywhere",
    "organization": "Poll Everywhere",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-03-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 95000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1187.5,
    "totalBondInvoice": 19850,
    "bondPayments": 19850,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Mukayila Alao",
    "role": "☆ Associate Software Engineer at The Knot Worldwide",
    "organization": "The Knot Worldwide",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-09-01",
    "endDate": "2024-03-01",
    "isCurrent": true,
    "salary": 95000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1187.5,
    "totalBondInvoice": 19000,
    "bondPayments": 17812.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Anas Nahil",
    "role": "☆ Entry Level Developer at Peloton",
    "organization": "Peloton",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-12-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 100000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1250,
    "totalBondInvoice": 24750,
    "bondPayments": 750,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Nima Sherpa",
    "role": "☆ Entry Level Developer at Peloton",
    "organization": "Peloton",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-01-01",
    "endDate": "2024-05-01",
    "isCurrent": true,
    "salary": 100000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1250,
    "totalBondInvoice": 20000,
    "bondPayments": 20000,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Shawn Faber",
    "role": "☆ Entry Level Developer at Peloton",
    "organization": "Peloton",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-12-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 100000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1250,
    "totalBondInvoice": 27200,
    "bondPayments": 6800,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Alex La Rosa Perez",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 800,
    "totalBondInvoice": 13600,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Alvi Rahman",
    "role": "☆ Summer Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-06-01",
    "endDate": "2022-08-01",
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 49765,
    "bondPayments": 49765,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Augusto Rupay",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 18375,
    "bondPayments": 2662.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Carlitos Dutan",
    "role": "Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": null,
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 3907.5,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Carlo Echeverri",
    "role": "☆ Software Engineer at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.15,
    "totalBondInvoice": 40612.65,
    "bondPayments": 16387.55,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Claire Petit Frere",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 3907.5,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Coreen Cooper",
    "role": "☆ Software Engineer at Moody's",
    "organization": "Moody's",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 49875,
    "bondPayments": 13068.75,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Dan Mazzilli",
    "role": "☆ Associate Software Engineer Rotation at Moody's",
    "organization": "Moody's",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 15275,
    "bondPayments": 15275,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Demi Jobi",
    "role": "☆ Software Developer at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 37687.5,
    "bondPayments": 5000,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Edwin Codrington",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-06-01",
    "endDate": "2023-08-01",
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 35437.5,
    "bondPayments": 16437.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Jamee Hengari",
    "role": "☆ Software Engineer at Moody's",
    "organization": "Moody's",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": "2023-04-01",
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 9187.5,
    "bondPayments": 9187.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Jenna Qian",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-06-01",
    "endDate": "2023-08-01",
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 1312.5,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Jessica Netto",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 51187.5,
    "bondPayments": 9187.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Jorge Carrera",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-06-01",
    "endDate": "2023-08-01",
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 28875,
    "bondPayments": 14281.26,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Joshua Nelson",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 2625,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "JuHao Chen",
    "role": "☆ Associate Software Engineer at Moody's",
    "organization": "Moody's",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 32812.5,
    "bondPayments": 30843.75,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Kalilah Clarke",
    "role": "☆ Associate Software Engineer at Moody's",
    "organization": "Moody's",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-07-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 32812.5,
    "bondPayments": 15168.75,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Keeanu Rodriguez",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 19687.5,
    "bondPayments": 18375,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Laiba Sajid",
    "role": "☆ Software Engineer at Thirty Madison",
    "organization": "Thirty Madison",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": "2024-03-01",
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 24937.5,
    "bondPayments": 8562.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Lina Ebreo",
    "role": "☆ Associate Software Engineer at Moody's",
    "organization": "Moody's",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 48562.5,
    "bondPayments": 15750,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Marsha Hall",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312,
    "totalBondInvoice": 47232,
    "bondPayments": 9060,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Mason Mei",
    "role": "☆ Associate Software Engineer Rotation at Moody's",
    "organization": "Moody's",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 31500,
    "bondPayments": 5250,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Meera Ramesh",
    "role": "☆ Associate Software Engineer Rotation at Moody's",
    "organization": "Moody's",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 15750,
    "bondPayments": 14437.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Naomi Pate",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 15750,
    "bondPayments": 10900,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Victor Lopez",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 13125,
    "bondPayments": 3937.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Yasser Saadi",
    "role": "☆ Analyst at Citi",
    "organization": "Citi",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-06-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 3937.5,
    "bondPayments": 1312.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Youssef Mohamed Farouk",
    "role": "☆ Associate Software Engineer Rotation at Moody's",
    "organization": "Moody's",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-08-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 105000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 8104.75,
    "bondPayments": 6736.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Antonio Martinez",
    "role": "☆ Software Engineer Boost Fellow at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": "2025-12-01",
    "isCurrent": true,
    "salary": 108000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 2700,
    "bondPayments": 3907.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Ayotunde Akinkunmi",
    "role": "☆ Software Engineer Boost Fellow at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": "2025-12-01",
    "isCurrent": true,
    "salary": 108000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1350,
    "totalBondInvoice": 9440,
    "bondPayments": 9420,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Ayyoub Belibel",
    "role": "☆ Software Engineer Boost Fellow at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 108000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1350,
    "totalBondInvoice": 10800,
    "bondPayments": 9420,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Camilo Paez",
    "role": "☆ Software Engineer Boost Fellow at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": "2025-12-01",
    "isCurrent": true,
    "salary": 108000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 3907.5,
    "bondPayments": 3907.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Gerardo Garcia Jr",
    "role": "☆ Software Engineer Boost Fellow at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 108000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 3907.5,
    "bondPayments": 3907.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Jorge Godoy Rodriguez",
    "role": "☆ Software Engineer Boost Fellow at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 108000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 3907.5,
    "bondPayments": 3907.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Lynnette Jacobs",
    "role": "☆ Software Engineer Boost Fellow at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 108000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 3907.5,
    "bondPayments": 3907.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Manoel Alves Teixeira",
    "role": "☆ Software Engineer Boost Fellow at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": "2025-12-01",
    "isCurrent": true,
    "salary": 108000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 3907.5,
    "bondPayments": 3907.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Marco Quispe",
    "role": "☆ Software Engineer Boost Fellow at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": "2025-12-01",
    "isCurrent": true,
    "salary": 108000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1350,
    "totalBondInvoice": 10800,
    "bondPayments": 6750,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Nasheed Jeremiah",
    "role": "☆ Software Engineer Boost Fellow at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 108000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 3907.5,
    "bondPayments": 3907.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Raymond Zhou",
    "role": "☆ Software Engineer Boost Fellow at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2025-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 108000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "10",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 3907.5,
    "bondPayments": 3907.5,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Ari Jackson",
    "role": "☆ Software Engineer at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 108160,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1352,
    "totalBondInvoice": 5000,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Bert Casale",
    "role": "☆ Software Engineer at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": "2024-12-01",
    "isCurrent": true,
    "salary": 108160,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1352,
    "totalBondInvoice": 13520,
    "bondPayments": 13520,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Christina Cephus",
    "role": "☆ Software Engineer at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": "2025-04-01",
    "isCurrent": true,
    "salary": 108160,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1352,
    "totalBondInvoice": 18928,
    "bondPayments": 16224,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Diego Carrero",
    "role": "☆ Software Engineer at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 108160,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1352,
    "totalBondInvoice": 5046,
    "bondPayments": 4056,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Jinseok Jung",
    "role": "☆ Software Engineer at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 108160,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1352,
    "totalBondInvoice": 13316,
    "bondPayments": 7260,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Joseph Rodriguez",
    "role": "☆ Software Engineer at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": "2024-12-01",
    "isCurrent": true,
    "salary": 108160,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1352,
    "totalBondInvoice": 10816,
    "bondPayments": 6760,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Marangely Rosas",
    "role": "☆ Software Engineer at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": "2025-04-01",
    "isCurrent": true,
    "salary": 108160,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1352,
    "totalBondInvoice": 17576,
    "bondPayments": 1352,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Raydelys Morrobel Reyes",
    "role": "☆ Software Engineer at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 108160,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1352,
    "totalBondInvoice": 17576,
    "bondPayments": 4604,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Vandhana Mohan",
    "role": "☆ Software Engineer at Uber",
    "organization": "Uber",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": "2025-04-01",
    "isCurrent": true,
    "salary": 108160,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "9",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1352,
    "totalBondInvoice": 0,
    "bondPayments": 0,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Abubakar Adams",
    "role": "☆ Cybersecurity Analyst at Blackstone",
    "organization": "Blackstone",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 110000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1375,
    "totalBondInvoice": 15812.5,
    "bondPayments": 3051,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Grace Bong",
    "role": "☆ Software Engineer Analyst at Blackstone",
    "organization": "Blackstone",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-07-01",
    "endDate": "2024-05-01",
    "isCurrent": true,
    "salary": 110000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1375,
    "totalBondInvoice": 26125,
    "bondPayments": 2750,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Isidro Molina",
    "role": "☆ Back End Engineer at Spring Health",
    "organization": "Spring Health",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-09-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 110000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1375,
    "totalBondInvoice": 33000,
    "bondPayments": 27500,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Josh Mendez",
    "role": "☆ Software Engineer I at JPMorgan Chase (JPMC)",
    "organization": "JPMorgan Chase (JPMC)",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-04-01",
    "endDate": "2024-01-01",
    "isCurrent": true,
    "salary": 110000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "7",
    "commit": false,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1375,
    "totalBondInvoice": 26125,
    "bondPayments": 26125,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Lili Huang",
    "role": "☆ Cybersecurity Analyst at Blackstone",
    "organization": "Blackstone",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2024-01-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 110000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1375,
    "totalBondInvoice": 27500,
    "bondPayments": 23375,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Fezz Narine",
    "role": "☆ Software Engineer Intern at SeatGeek",
    "organization": "SeatGeek",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": "2023-02-01",
    "isCurrent": true,
    "salary": 112000,
    "salaryBand": null,
    "permTemp": "Temporary",
    "employeeType": null,
    "isaEligible": true,
    "cohort": "7",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1400,
    "totalBondInvoice": 11200,
    "bondPayments": 4200,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Rohan Sterling",
    "role": "☆ Software Engineer at Thirty Madison",
    "organization": "Thirty Madison",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2022-08-01",
    "endDate": "2025-01-01",
    "isCurrent": true,
    "salary": 112000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Former",
    "monthlyBondInvoice": 1312.5,
    "totalBondInvoice": 36749,
    "bondPayments": 28875,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Bryant Mercedes Canela",
    "role": "☆ Fullstack Engineer at Poll Everywhere",
    "organization": "Poll Everywhere",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-03-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 120000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1500,
    "totalBondInvoice": 37400,
    "bondPayments": 26900,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  },
  {
    "fellow": "Jerry De Jesus",
    "role": "☆ Software Developer I at Poll Everywhere",
    "organization": "Poll Everywhere",
    "yearStart": null,
    "yearEnd": null,
    "startDate": "2023-03-01",
    "endDate": null,
    "isCurrent": true,
    "salary": 120000,
    "salaryBand": null,
    "permTemp": "Permanent",
    "employeeType": "Employee",
    "isaEligible": true,
    "cohort": "8",
    "commit": true,
    "employedStatus": "Current",
    "monthlyBondInvoice": 1500,
    "totalBondInvoice": 37500,
    "bondPayments": 37400,
    "bondSalaryThreshold": 50000,
    "incomeSharePct": 15,
    "currentlyInvoicing": false
  }
];

export const bondJobChanges = [
  {
    "name": "Anthony Cannonier",
    "salary": 90000,
    "title": "Schools Senior Data Specialist at Democracy Prep Public Schools",
    "startDate": "2024-07-01",
    "invoiceStart": "2025-01-20",
    "monthly": 1125,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Xavier Rice",
    "salary": null,
    "title": "Safety Operations Associate at Feeld",
    "startDate": "2025-01-01",
    "invoiceStart": "2025-02-20",
    "monthly": null,
    "contract": true,
    "notes": "Laid off"
  },
  {
    "name": "Jorge Godoy Rodriguez",
    "salary": 108000,
    "title": "Software Engineer Boost Fellow",
    "startDate": "2025-01-13",
    "invoiceStart": "2025-02-20",
    "monthly": 1350,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Nasheed Jeremiah",
    "salary": 108000,
    "title": "Software Engineer Boost Fellow",
    "startDate": "2025-01-13",
    "invoiceStart": "2025-02-20",
    "monthly": 1350,
    "contract": true,
    "notes": "Not on AutoPay"
  },
  {
    "name": "Lynette Jacobs",
    "salary": 108000,
    "title": "Software Engineer Boost Fellow",
    "startDate": "2025-01-13",
    "invoiceStart": "2025-02-20",
    "monthly": 1350,
    "contract": true,
    "notes": "Not on AutoPay"
  },
  {
    "name": "Ayyoub Belibel",
    "salary": 108000,
    "title": "Software Engineer Boost Fellow",
    "startDate": "2025-01-13",
    "invoiceStart": "2025-02-20",
    "monthly": 1350,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Runquan Zhou",
    "salary": 108000,
    "title": "Software Engineer Boost Fellow",
    "startDate": "2025-01-13",
    "invoiceStart": "2025-02-20",
    "monthly": 1350,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Gerardo Garcia Jr.",
    "salary": 108000,
    "title": "Software Engineer Boost Fellow",
    "startDate": "2025-01-13",
    "invoiceStart": "2025-02-20",
    "monthly": 1350,
    "contract": true,
    "notes": "3 month pause"
  },
  {
    "name": "Manoel Alves Teixeira",
    "salary": 108000,
    "title": "Software Engineer Boost Fellow",
    "startDate": "2025-01-13",
    "invoiceStart": "2025-02-20",
    "monthly": 1350,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Antonio Martinez",
    "salary": 108000,
    "title": "Software Engineer Boost Fellow",
    "startDate": "2025-01-13",
    "invoiceStart": "2025-02-20",
    "monthly": 1350,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Marco Quispe",
    "salary": 108000,
    "title": "Software Engineer Boost Fellow",
    "startDate": "2025-01-13",
    "invoiceStart": "2025-02-20",
    "monthly": 1350,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Ayotunde Akinkunmi",
    "salary": 108000,
    "title": "Software Engineer Boost Fellow",
    "startDate": "2025-01-13",
    "invoiceStart": "2025-02-20",
    "monthly": 1350,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Camilo Paez",
    "salary": 108000,
    "title": "Software Engineer Boost Fellow",
    "startDate": "2025-01-13",
    "invoiceStart": "2025-02-20",
    "monthly": 1350,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Karan Taneja",
    "salary": 160000,
    "title": "SWE II at Peloton",
    "startDate": "2025-01-21",
    "invoiceStart": "2025-02-20",
    "monthly": 2000,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Chantal Gomez",
    "salary": 85000,
    "title": "Software Engineer at Red Canary",
    "startDate": "2025-01-21",
    "invoiceStart": "2025-02-20",
    "monthly": 1062.5,
    "contract": true,
    "notes": "Not on AutoPay"
  },
  {
    "name": "Akira Brown",
    "salary": 75000,
    "title": "Software Engineer at Red Canary",
    "startDate": "2025-01-25",
    "invoiceStart": "2025-02-20",
    "monthly": 937.5,
    "contract": true,
    "notes": "Not on AutoPay"
  },
  {
    "name": "Carlitos Dutan",
    "salary": 105000,
    "title": "Software Engineer at Citi",
    "startDate": "2025-06-02",
    "invoiceStart": "2025-07-20",
    "monthly": 1312.5,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Claire Petit Frere",
    "salary": 105000,
    "title": "Software Engineer at Citi",
    "startDate": "2025-06-02",
    "invoiceStart": "2025-07-20",
    "monthly": 1312.25,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Joshua Nelson",
    "salary": 105000,
    "title": "Software Engineer at Citi",
    "startDate": "2025-06-02",
    "invoiceStart": "2025-07-20",
    "monthly": 1312.5,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Yasser Saadi",
    "salary": 105000,
    "title": "Software Engineer at Citi",
    "startDate": "2025-06-02",
    "invoiceStart": "2025-07-20",
    "monthly": 1312.5,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Brenda Soto",
    "salary": 80000,
    "title": "Software Engineer at Citizens",
    "startDate": "2025-07-07",
    "invoiceStart": null,
    "monthly": 1000,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Hector Zhong",
    "salary": 80000,
    "title": "Software Engineer at Citizens",
    "startDate": "2025-07-07",
    "invoiceStart": "2025-08-20",
    "monthly": 1000,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Kevin Brutus",
    "salary": 80000,
    "title": "Cybersecurity at Citizens",
    "startDate": "2025-07-07",
    "invoiceStart": null,
    "monthly": null,
    "contract": true,
    "notes": "Only has 1 more invoice to pay off and would pay half each time over the first 2 months of his new employment"
  },
  {
    "name": "Uduakabasi Abasiurua",
    "salary": null,
    "title": "",
    "startDate": null,
    "invoiceStart": null,
    "monthly": null,
    "contract": null,
    "notes": "Void invoices since June 2024. Has been unemployed since then."
  },
  {
    "name": "Joseph Rodriguez",
    "salary": null,
    "title": "",
    "startDate": null,
    "invoiceStart": null,
    "monthly": null,
    "contract": null,
    "notes": "Stop invoicing, laid off from Uber fellowship"
  },
  {
    "name": "Christina Loiacono",
    "salary": 80000,
    "title": "Cybersecurity at Citizens",
    "startDate": "2025-07-07",
    "invoiceStart": "2025-08-20",
    "monthly": 1000,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Justin Overton",
    "salary": 80000,
    "title": "Cybersecurity at Citizens",
    "startDate": "2025-07-07",
    "invoiceStart": "2025-08-20",
    "monthly": 1000,
    "contract": true,
    "notes": ""
  },
  {
    "name": "Bert Casale",
    "salary": null,
    "title": "Need to verify with Commit team",
    "startDate": null,
    "invoiceStart": null,
    "monthly": null,
    "contract": false,
    "notes": "Uber full-time conversion - new salary"
  },
  {
    "name": "Juan Feliz",
    "salary": null,
    "title": "Need to verify with Commit team",
    "startDate": null,
    "invoiceStart": null,
    "monthly": null,
    "contract": false,
    "notes": "Uber full-time conversion - new salary"
  },
  {
    "name": "Ari Jackson",
    "salary": null,
    "title": "Need to verify with Commit team",
    "startDate": null,
    "invoiceStart": null,
    "monthly": null,
    "contract": false,
    "notes": "Uber full-time conversion - new salary"
  },
  {
    "name": "Jinseok Jung",
    "salary": null,
    "title": "Need to verify with Commit team",
    "startDate": null,
    "invoiceStart": null,
    "monthly": null,
    "contract": false,
    "notes": "Uber full-time conversion - new salary"
  },
  {
    "name": "Raydelys Morrobel Reyes",
    "salary": null,
    "title": "Need to verify with Commit team",
    "startDate": null,
    "invoiceStart": null,
    "monthly": null,
    "contract": false,
    "notes": "Uber full-time conversion - new salary"
  },
  {
    "name": "Ariel Chen",
    "salary": 97760,
    "title": "",
    "startDate": "2026-05-04",
    "invoiceStart": "2026-06-20",
    "monthly": 1222,
    "contract": null,
    "notes": ""
  },
  {
    "name": "Jacob Williams",
    "salary": 97760,
    "title": "",
    "startDate": "2026-05-04",
    "invoiceStart": "2026-06-20",
    "monthly": 1222,
    "contract": null,
    "notes": ""
  },
  {
    "name": "Kelvin Saldana",
    "salary": 97760,
    "title": "",
    "startDate": "2026-05-04",
    "invoiceStart": "2026-06-20",
    "monthly": 1222,
    "contract": null,
    "notes": ""
  },
  {
    "name": "Josue Villalona",
    "salary": 105000,
    "title": "",
    "startDate": "2026-05-26",
    "invoiceStart": "2026-06-20",
    "monthly": 1312.5,
    "contract": null,
    "notes": ""
  }
];

export const layoffHistory = [
  {
    "name": "Joseph Rodriguez",
    "date": "2024-12-01"
  },
  {
    "name": "Richard Green",
    "date": "2024-04-01"
  },
  {
    "name": "Uduakabasi Abasiurua",
    "date": "2024-06-01"
  },
  {
    "name": "Sheriff Ameen",
    "date": "2024-10-01"
  },
  {
    "name": "Bert Casale",
    "date": "2024-12-01"
  },
  {
    "name": "Victoria Buchanan",
    "date": "2025-01-01",
    "detail": "Quit"
  },
  {
    "name": "Rohan Sterling",
    "date": "2025-01-01"
  },
  {
    "name": "Angelina Ebreo",
    "date": "2025-03-01"
  },
  {
    "name": "Douglas MacKrell",
    "date": "2025-03-01"
  },
  {
    "name": "Jerry de Jesus",
    "date": "2025-04-01"
  },
  {
    "name": "Tia Lendor",
    "date": "2025-04-01"
  },
  {
    "name": "Antonio Martinez",
    "date": "2025-04-01"
  },
  {
    "name": "Bryant Mercedes Canela",
    "date": "2025-04-01"
  },
  {
    "name": "Hady Mohamed",
    "date": "2025-04-01"
  },
  {
    "name": "Xavier Rice",
    "date": "2025-04-01"
  },
  {
    "name": "Clifford Charles",
    "date": "2025-04-01"
  },
  {
    "name": "Stephanie Lucano",
    "date": "2025-05-01"
  },
  {
    "name": "Krishan Roy",
    "date": "2025-03-01"
  },
  {
    "name": "Marsha Hall",
    "date": "2025-07-01"
  },
  {
    "name": "JuHao Chen",
    "date": "2025-07-01"
  },
  {
    "name": "Isidro Molina",
    "date": "2025-07-01"
  },
  {
    "name": "Adrian Burke",
    "date": "2025-08-01",
    "detail": "Cohort 9"
  },
  {
    "name": "Nilber Remon",
    "date": "2025-08-01",
    "detail": "Cohort 6"
  },
  {
    "name": "Marangely Rosas",
    "date": "2025-04-01"
  },
  {
    "name": "Vandhana Mohan",
    "date": "2025-04-01"
  },
  {
    "name": "Christina Cephus",
    "date": "2025-04-01"
  },
  {
    "name": "Emalee Soto",
    "date": "2025-10-01",
    "detail": "Cohort 8"
  },
  {
    "name": "Samantha Figueroa",
    "date": "2025-10-01",
    "detail": "Cohort 8"
  },
  {
    "name": "Ayyoub Belibel",
    "date": "2025-12-01",
    "detail": "Cohort 10"
  },
  {
    "name": "Nasheed Jeremiah",
    "date": "2025-12-01",
    "detail": "Cohort 10"
  },
  {
    "name": "John Prado",
    "date": "2026-02-01",
    "detail": "Cohort 8"
  }
];

export const pauseHistory = [
  {
    "name": "Gerardo Garcia",
    "period": "2/25-4/25"
  },
  {
    "name": "Hady Mohamed",
    "period": "4/25"
  },
  {
    "name": "Anthony Cannonier",
    "period": "5/25-7/25"
  },
  {
    "name": "Jorge Carrera",
    "period": "5/25-until response"
  },
  {
    "name": "Joshua Mendez",
    "period": ""
  },
  {
    "name": "Teyanna Earle",
    "period": ""
  },
  {
    "name": "Jinseok Jung",
    "period": "9/24-3/25"
  },
  {
    "name": "Victor Lopez",
    "period": ""
  }
];
