"""Research recommendations — actionable findings from org intelligence.

Sprint 4: generated by investigate_connected_orgs().
Sprint 4.5: consumed by CRM write agent tools.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class ResearchRecommendation(BaseModel):
    """A recommended action discovered during research."""

    recommendation_type: Literal["investigate_org", "create_account", "create_contact"]
    entity_name: str
    entity_type: Literal["account", "contact", "organization"]
    rationale: str
    supporting_claims: list[str] = []
    priority: Literal["high", "medium", "low"] = "medium"
    status: str = "pending"
    crm_match: dict | None = None
    metadata: dict = {}
